name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.output.outputs.helloworld }}
    steps:
      - uses: actions/checkout@v3
      - name: Read test result
        if: always()
        run: |
          cat test_report.txt
      - name: Run a one-line script
        id: output
        run: |
          echo "| Test suites | Assertion | Pass | Failure |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| 4 | 12 | 11 | 1 |" >> $GITHUB_STEP_SUMMARY
