name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.output.outputs.helloworld }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        id: output
        run: echo "::set-output name=helloworld::helloworld"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
