name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.output.outputs.helloworld }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        id: output
        run: |
          echo "| foo | bar |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| baz | bim |" >> $GITHUB_STEP_SUMMARY
